CREATE TABLE TVMS_CARRIER
(
	CARRIERID INT NOT NULL PRIMARY KEY,
	CARRIERNAME VARCHAR(100) ,
	CREATEDBY  INT,
	CREATEDTIMESTAMP  TIMESTAMP,
	LASTMODIFIEDBY	INT,
	LASTMODIFIEDTIMESTAMP  TIMESTAMP,
	FREEZE	INT(4)
);

CREATE TABLE TVMS_CARRIERADRESS
(
		CARRIERADRESSID BIGINT NOT NULL PRIMARY KEY,
		CARRIERID INT,
		ADRESSTYPE INT,
		ZIPCODE  VARCHAR(6),
		ADRESS1 VARCHAR(100),
		ADRESS2 VARCHAR(150),
		CREATEBY INT,
		CREATEDTIMESTAMP  TIMESTAMP,
		LASTMODIFIEDBY	INT,
		LASTMODIFIEDTIMESTAMP  TIMESTAMP,
		MOBILENUMBER VARCHAR(20),
		PHONEAREACODER VARCHAR(20),
		PHONENUMBER VARCHAR(30),
		FAXAREACODE VARCHAR(20),
		FAXNUMBER VARCHAR(30),
		CONTACTPERSON VARCHAR(100)
);

CREATE TABLE TSCM_SUPPLIERMASTER
(
	SUPPLIERID INT NOT NULL PRIMARY KEY,
	SUPPLIERNAME VARCHAR(300),
	SUPPLIERGNO VARCHAR(100),
	CREATEBY INT,
	CREATEDTIMESTAMP  TIMESTAMP,
	LASTMODIFIEDBY	INT,
	LASTMODIFIEDTIMESTAMP  TIMESTAMP,
	FREEZE INT(4)
);

CREATE TABLE TSCM_SUPPLIERADDRESS
(
	SUPPLIERADDRESSID  BIGINT NOT NULL PRIMARY KEY,
	SUPPLIERID INT,
	ADRESSTYPE INT,
	ZIPCODE  VARCHAR(6),
	ADRESS1 VARCHAR(100),
	ADRESS2 VARCHAR(150),
	CREATEBY INT,
	CREATEDTIMESTAMP  TIMESTAMP,
	LASTMODIFIEDBY	INT,
	LASTMODIFIEDTIMESTAMP  TIMESTAMP,
	MOBILENUMBER VARCHAR(20),
	PHONEAREACODER VARCHAR(20),
	PHONENUMBER VARCHAR(30),
	FAXAREACODE VARCHAR(20),
	FAXNUMBER VARCHAR(30),
	CONTACTPERSON VARCHAR(100) 
);


